---
site_name: {{ cookiecutter.project_name }} Docs
repo_url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.repo_name }}
dev_addr: "0.0.0.0:4000"
theme: bootstrap
docs_dir: docs
